name: CI/CD LyricsScraperApi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lyrics_scraper_api-cicd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/LyricsScraperApi.sln
    - name: Build
      run: dotnet build src/LyricsScraperApi.sln --no-restore --configuration Release --verbosity minimal
    - name: Test (Unit) with Coverage
      run: |
        dotnet test src/LyricsScraperApi.UnitTests/LyricsScraperApi.UnitTests.csproj \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --settings coverlet.runsettings
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./TestResults/**/*.cobertura.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
